### ISSUE TITLE
Un-list Mipmap Web Example?

### ISSUE THREAD

**Issue by zicklag** [gfx-rs/wgpu-rs.github.io#23]
The WebGL mipmapping example doesn't really work right, should we remove it from the list on the website?

![image](https://user-images.githubusercontent.com/25393315/172026067-d181655e-e7fb-43a7-8c8e-6342fd762ed0.png)

**Comment by grovesNL** [comment]
We should keep the web example for WebGPU, but maybe we could change how it works or disable it for WebGL only?

**Comment by zicklag** [comment]
Yeah, the WebGPU example page has a separate list of examples, so we could just take it off of the WebGL example list.

As far as changing how it works, I'm not sure if there's any way to support mipmaps or otherwise "fake" them and make them just look un-mip-mapped, but that would probably be the best long-term solution if possible.

I dont' know enough about it to know whether or not that would be feasible.

**Comment by cwfitzgerald** [comment]
This is now fixed
